### ISSUE TITLE
Fixed block size

### ISSUE THREAD

**Issue by mpariente** [bastibe/SoundCard#10]
Hi, 

Is there a way to record continuously with a fixed blocksize? 
I notice that even when specifying the blocksize in the recorder, the actual blocksize varies which is not convenient in my case. I saw that it is specified in the doc of the function itself but I wonder if there is a way to force the blocksize to be fixed.

Thanks in advance

**Comment by mpariente** [comment]
Why would there be a gap between the two calls? 
We also make the hypothesis that the new data is the continuation of the previous data when we create a continuous record and play stream (example in the README), don't we? 
So if it works in the example, I don't see any reason why it shouldn't work. 

I'm ready to spend some time implementing this but before I'd like to discuss some details first :
* I'm thinking on adding `fix_blocksize` argument to either the `_Recorder` class or the `record` method, in order to give the user the choice
* We should implement kind of a `flush` method in the `_Recorder` class so we don't throw away any of the data (if we don't want to). 

What do you think?

**Comment by bastibe** [comment]
This discussion is being continued in @11.
