### ISSUE TITLE
soundcard does not print anything anymore (MacOS Big sur/ M1)

### ISSUE THREAD

**Issue by fvviz** [bastibe/SoundCard#134]
hey, so im using soundcard for a project so i ran this code from the docs

```py
import soundcard as sc

# get a list of all speakers:
speakers = sc.all_speakers()
# get the current default speaker on your system:
default_speaker = sc.default_speaker()
# get a list of all microphones:
mics = sc.all_microphones()
# get the current default microphone on your system:
default_mic = sc.default_microphone()

print(speakers)
```

when i did this a week ago it worked fine. But now, when i tried this same code   i got a new error
```
Traceback (most recent call last):
  File "/Users/faizrahim/Desktop/codestuff/brah.py", line 12, in <module>
    print(speakers)
  File "/Users/faizrahim/Library/Python/3.9/lib/python/site-packages/soundcard/coreaudio.py", line 164, in __repr__
    return '<Speaker {} ({} channels)>'.format(self.name, self.channels)
  File "/Users/faizrahim/Library/Python/3.9/lib/python/site-packages/soundcard/coreaudio.py", line 134, in name
    return _CoreAudio.CFString_to_str(name)
  File "/Users/faizrahim/Library/Python/3.9/lib/python/site-packages/soundcard/coreaudio.py", line 297, in CFString_to_str
    assert err == 1, "Could not decode string"
AssertionError: Could not decode string
[Finished in 452ms with exit code 1]
```

Where did this random error come from all of a sudden and how can i fix it?

**Comment by fvviz** [comment]
oh no its back again

**Comment by bastibe** [comment]
What is the name of the sound card in question, and what are your locale settings?

**Comment by fvviz** [comment]
I figured out the issue, I was using my AirPods which were called `Faiz's Airpods`. Im guessing the `'` in the name of the device caused the issue? Anyway I renamed my AirPods and it worked just fine

**Comment by bastibe** [comment]
Thank you for following up on this, and congratulations for finding a workaround. It's still a bug on my end, though. Could you tell me your locale settings and an add an exact copy-and-paste of the sound card's name? That would help me track down the cause of this issue.
