### ISSUE TITLE
python 3.10 incompatibility

### ISSUE THREAD

**Issue by juligreen** [bastibe/SoundCard#140]
Because of deprecation `collections.Iterable` has to be replaced with `collections.abc.Iterable`.

Usage of `collections.Iterable`:
```
mediafoundation.py
490:        elif isinstance(channels, collections.Iterable):

pulseaudio.py
638:        if isinstance(self.channels, collections.Iterable):
651:        if isinstance(self.channels, collections.Iterable):

coreaudio.py
468:        if isinstance(channels, collections.Iterable):
```

**Comment by bastibe** [comment]
Thank you for the heads-up. Would you like to contribute the change as a pull request?

**Comment by juligreen** [comment]
Done :v: 

I get some failures in the tests, but that's also the case before the change in older versions

**Comment by bastibe** [comment]
Yes, the tests are a bit fickle, regrettably, as they partly depend on a properly configured sound card.

Anyway, thank you! And a merry Christmas if that's your thing!

**Comment by juligreen** [comment]
Thank you too for maintaining this package!

And merry Christmas to you too!
