### ISSUE TITLE
Support acoustic echo cancellation (AEC) for windows

### ISSUE THREAD

**Issue by truongdo** [bastibe/SoundCard#145]
I'm using soundcard to develop a audio recording program. However, it looks like the library doesn't support for AEC, which cancel out audio playing from the speaker.

It would be great to have AEC integrated to soundcard. Do you think it is possible to do so?

**Comment by bastibe** [comment]
That's out of scope for soundcard, sorry. But feel free to build an AEC system on top of soundcard.
