### ISSUE TITLE
Publish version 0.1.2

### ISSUE THREAD

**Issue by adzialocha** [bastibe/SoundCard#19]
It looks like Version `0.1.2` was not published on PyPi yet, right now I have to use dependency_links in my `setup.py` to point on the github repository to use the latest version (with channel maps). It would be great if you could publish that version! Thank you! And thank you for this amazing library!

**Comment by bastibe** [comment]
Thank you for reminding me! The current version should be available on PyPI now. Can you verify that it works for you?

**Comment by adzialocha** [comment]
@bastibe it works! Thank you for your fast answer!
