### ISSUE TITLE
cannot playback on linux

### ISSUE THREAD

**Issue by buscon** [bastibe/SoundCard#20]
hi,

I'm trying out the library on linux, the playback does not seem to work.
I tryed your example, everything work but when i do the playback i get:
default_speaker.play(data/numpy.max(data), samplerate=48000)
Assertion 's' failed at pulse/stream.c:1412, function pa_stream_connect_record(). Aborting.

what can I do?
How can I select jack instead of pulseaudio? I guess that might fix the problem...

thanks and best wishes.

**Comment by bastibe** [comment]
You need to have a correctly set-up pulseaudio for SoundCard to work. SoundCard does not support Jack or ALSA.

**Comment by buscon** [comment]
i actually do have a set up and working pulseaudio soundcard, i usually use that. I thought jack might have helped.

How can I debug the pulseaudio issue?

thanks

**Comment by bastibe** [comment]
What version of Linux and pulseaudio are you running?

**Comment by bastibe** [comment]
Can you tell me the complete stack trace? It doesn't seem toale sense that "play" would call "connect_record".

**Comment by bastibe** [comment]
Can you tell me how many input and output channels SoundCard reports for your default device?

**Comment by buscon** [comment]
In the meanwhile it does work, though I did not change anything... very strange!

I am on Linux mint 18.2, pulseaudio 8.0.
I am using my internal sound card, 2 inputs and 2 outputs. I tried with my external sound card (fully running on linux) but i got the same issue.

I will keep an eye on the issue and report back if I manage to understand the problem.
