### ISSUE TITLE
Problems with the demo

### ISSUE THREAD

**Issue by Ninja243** [bastibe/SoundCard#24]
I'd like to get the loopback example on the front page working, but I am getting the error below when trying to run it. I am attempting to run this using Python 3.6 on Linux. Not sure if this is related to [this issue](https://github.com/bastibe/SoundCard/issues/20) or not.

`File "/usr/local/lib/python3.6/dist-packages/soundcard/pulseaudio.py", line 417, in record
    chunk = self._record_chunk()
  File "/usr/local/lib/python3.6/dist-packages/soundcard/pulseaudio.py", line 371, in _record_chunk
    readable_bytes = self._pulse._pa_stream_readable_size(self.stream)
AttributeError: '_Recorder' object has no attribute '_pulse'
`

**Comment by Ninja243** [comment]
Yeah, pulseaudio version 10.0.

**Comment by bastibe** [comment]
Can you please state exactly what code you are trying to run?

**Comment by Ninja243** [comment]
The second block of code under the[ tutorial section of the main page](https://github.com/bastibe/SoundCard#tutorial).

**Comment by bastibe** [comment]
The second block alone is not executable. This can not be true.

Please state exactly what code you are trying to run, as a complete Python script, so I can reproduce your error on my end. Help me help you.

What does soundcard report as your `default_mic` and `default_speaker`?

**Comment by Ninja243** [comment]
[This](https://pastebin.com/jvDnCGF1) is the script I tried to run. I cannot reproduce the error anymore so I think this issue can be marked as solved. The default mic is `<Microphone Built-in Audio Analog Mono (2 channels)>` and the default speaker is `<Speaker FFT based equalizer on Built-in Audio Analog Stereo (2 channels)>`.

**Comment by chakradarraju** [comment]
I'm seeing same error
```
Traceback (most recent call last):
  File "record.py", line 12, in <module>
    f.writeframes(rcdr.record(44100))
  File "/home/chakradarraju/.virtualenvs/py3/lib/python3.6/site-packages/soundcard/pulseaudio.py", line 588, in record
    chunk = self._record_chunk()
  File "/home/chakradarraju/.virtualenvs/py3/lib/python3.6/site-packages/soundcard/pulseaudio.py", line 528, in _record_chunk
    readable_bytes = self._pulse._pa_stream_readable_size(self.stream)
AttributeError: '_Recorder' object has no attribute '_pulse'
```

code:
```
import soundcard as sc
import wave

lb = sc.all_microphones(include_loopback=True)[0]
rcdr = lb.recorder(44100)

with wave.open('recorded.wav', 'wb') as f:
    f.writeframes(rcdr.record(44100))
```

I'm on ubuntu 18.04 with pulseaudio 11.1

**Comment by bastibe** [comment]
I'll have a look.

**Comment by srikaratstrings** [comment]
Hello,

I'm facing the exact same issue with this code
import soundcard as sc
import wave

lb = sc.all_microphones(include_loopback=True)[0]
rcdr = lb.recorder(44100)

with wave.open('recorded.wav', 'wb') as f:
    f.writeframes(rcdr.record(44100))

pulseaudio 11.1
Python 3.6.7
Ubuntu 18.04

**Comment by srikaratstrings** [comment]
Sorry about that. This has been resolve. This was an error on my part. Thanks!

**Comment by bastibe** [comment]
> I'm seeing same error
> 
> ```
> Traceback (most recent call last):
>   File "record.py", line 12, in <module>
>     f.writeframes(rcdr.record(44100))
>   File "/home/chakradarraju/.virtualenvs/py3/lib/python3.6/site-packages/soundcard/pulseaudio.py", line 588, in record
>     chunk = self._record_chunk()
>   File "/home/chakradarraju/.virtualenvs/py3/lib/python3.6/site-packages/soundcard/pulseaudio.py", line 528, in _record_chunk
>     readable_bytes = self._pulse._pa_stream_readable_size(self.stream)
> AttributeError: '_Recorder' object has no attribute '_pulse'
> ```
> 
> code:
> 
> ```
> import soundcard as sc
> import wave
> 
> lb = sc.all_microphones(include_loopback=True)[0]
> rcdr = lb.recorder(44100)
> 
> with wave.open('recorded.wav', 'wb') as f:
>     f.writeframes(rcdr.record(44100))
> ```
> 
> I'm on ubuntu 18.04 with pulseaudio 11.1

The recorder is a context manager. You'll have to use it with `with`.
