### ISSUE TITLE
what is minimum version of OSX ?

### ISSUE THREAD

**Issue by vichug** [bastibe/SoundCard#27]
Hello, not really an issue, but i wanted to know if OSX versions prior to macOS (mine is 10.10) were susceptible to work with SoundCard. If not, any idea if it was possible to make it backward-compatible ; and the amount of work that it would require ? Thanks ! ps: sorry for polluting the issues section with this. Not sure where this kind of question should go.

**Comment by bastibe** [comment]
No idea. But Core Audio has been around basically since OS X 10.0, so SoundCard *should* work with any version of macOS from the last ten years or so. I haven't tried it, though, and I don't have old macOS hardware available to try it.

**Comment by vichug** [comment]
ok, wil try that eventually and report.
