### ISSUE TITLE
Recording with numframes=None does not work on Linux

### ISSUE THREAD

**Issue by slole** [bastibe/SoundCard#28]
`input.record(None, samplerate)` does not work in Linux. I get the following error: 
```
Traceback (most recent call last):
  File "ffttest.py", line 24, in <module>
    data = input.record(None, samplerate)
  File "/home/jan/Development/musicled/audiotest/soundcard/pulseaudio.py", line 212, in record
    return r.record(numframes)
  File "/home/jan/Development/musicled/audiotest/soundcard/pulseaudio.py", line 425, in record
    [-1, self.channels]))
TypeError: 'list' object cannot be interpreted as an integer
```

I went into the source and changed the line: `return numpy.reshape(numpy.concatenate([self.flush(), self._record_chunk()], [-1, self.channels]))` to `return numpy.reshape(self._record_chunk(), [-1, self.channels])` and it works but it now ignores the buffer I guess.

**Comment by bastibe** [comment]
Can you send me a complete example code, so I can reproduce the issue?

**Comment by slole** [comment]
Here it is:
```
import soundcard

input = soundcard.all_microphones(include_loopback=True)[0]

samplerate = 48000

while True:
	data = input.record(None, samplerate)
	print("recorded data")
```

**Comment by slole** [comment]
Oh and it also doesn't work when calling it not in a loop or when using the `recorder` object.

**Comment by bastibe** [comment]
Thank you. I will investigate.

**Comment by bastibe** [comment]
Hi @slole, I believe I fixed the issue in 78ff9c3. Could you check that your issue is truly fixed?

**Comment by slole** [comment]
I'll get right on it asap.

**Comment by slole** [comment]
Tested, it works.
