### ISSUE TITLE
Crash when recording in small chunks (only on Linux).

### ISSUE THREAD

**Issue by slole** [bastibe/SoundCard#29]
When recording with small `numframes` (below 2400 or so) I get the following error: `Assertion 's' failed at pulse/stream.c:1411, function pa_stream_connect_record(). Aborting.
Aborted (core dumped)`

**Comment by bastibe** [comment]
Can you send me some example code so I can reproduce the issue?

**Comment by slole** [comment]
Here it is: 
```
import soundcard

input = soundcard.all_microphones(include_loopback=True)[0]

samplerate = 48000
chunk = 2400

while True:
	data = input.record(chunk, samplerate)
	print("recorded data")
```

**Comment by slole** [comment]
OK, i guess that isn't the intended use-case and it works when using:
```
import soundcard

input = soundcard.all_microphones(include_loopback=True)[0]

samplerate = 48000
chunk = 2400

with input.recorder(samplerate) as mic:
    while True:
        data = mic.record(chunk)
        print("recorded data")
```

It would probably still be a good idea to find what is the problem.

**Comment by bastibe** [comment]
Yes, that would explain it. Depending on your native block size, the `record` method will return instantly, and flood pulseaudio with new instances. 

I will close this issue, and investigate this further in #28.

**Comment by drscotthawley** [comment]
I just tried my [oscilloscope app](https://gist.github.com/drscotthawley/7c0a8b0f95d2c101ea3392ed6af85a63) (which works fine on Mac) on Linux, and got exactly this error.  My numframes is equal to 1024. 
Used a brand-new install of soundcard via pip.  Should I open up a new issue?

**Comment by bastibe** [comment]
Please open a new issue with a piece of example code and the exact error message.
