### ISSUE TITLE
Prevent audio volume changing when recording with include_loopback

### ISSUE THREAD

**Issue by slole** [bastibe/SoundCard#33]
Is there a way to get the audio volume (as a system setting) and increase the volume when recording to adjust for the lower audio volume? This wouldn't be an issue, it is just a good idea to preserve consistency with Windows, since the volume of the recording does not change when changing the system volume.

**Comment by bastibe** [comment]
Not in SoundCard. SoundCard is currently not concerned with volumes at all. Come to think of it, this might be an interesting feature idea for the future, but it currently does not touch volumes anywhere.

However, audio volume is typically just a constant multiplication factor, which is easy to apply manually.

**Comment by slole** [comment]
Ok, I'll look around if there is an easy way of checking the system audio volume level with python and adjust for it. If I find a sensible solution I'll make a pull request.

**Comment by bastibe** [comment]
cool!
