### ISSUE TITLE
How to stop streaming?

### ISSUE THREAD

**Issue by jundengdeng** [bastibe/SoundCard#35]
Hi Bastibe

First of all, thanks a lot for sharing this project. 

In pyaduio, there is a way to start or stop streaming. Here, I'd like to know if there is a way to allow an Microphone object to explicitly exit the real-time streaming.

The example code is like the following:
```
import soundcard as sc
import numpy

# get the current default microphone on your system:
default_mic = sc.default_microphone()
data = default_mic.record(samplerate=48000, numframes=48000)
# Can I stop streaming?
```

Thanks for your time!

Jun

**Comment by bastibe** [comment]
The `record` method will stop automatically once `numframes` samples have been recorded. Use the `recorder` context manager to record continuously.
