### ISSUE TITLE
TypeError(f'Invalid kind: {kind}' observed when importing soundcard

### ISSUE THREAD

**Issue by vasudev2222** [bastibe/SoundCard#37]
I have installed python soundcard module and when importing soundcard I see the below error:

C:\Users\HP>pip install soundcard
Requirement already satisfied: soundcard in c:\python27\lib\site-packages (0.1.2)
Requirement already satisfied: numpy in c:\python27\lib\site-packages (from soundcard) (1.13.1+mkl)
Requirement already satisfied: cffi in c:\python27\lib\site-packages (from soundcard) (1.11.5)
Requirement already satisfied: pycparser in c:\python27\lib\site-packages (from cffi->soundcard) (2.18)

C:\Users\HP>python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import soundcard as sd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\soundcard\__init__.py", line 8, in <module>
    from soundcard.mediafoundation import *
  File "C:\Python27\lib\site-packages\soundcard\mediafoundation.py", line 196
    raise TypeError(f'Invalid kind: {kind}')
                                          ^
SyntaxError: invalid syntax
>>>

**Comment by Warniz** [comment]
The project is written for python3, that's probably the reason for the syntax error. Try installing it with python3

**Comment by bastibe** [comment]
Exactly, SoundCard is Pyhon 3 only.
