### ISSUE TITLE
Python 3.5 Support

### ISSUE THREAD

**Issue by dkumor** [bastibe/SoundCard#45]
Hi! I would like to use this library on a Raspberry Pi to gather audio data. Unfortunately, the Pi is currently stuck at Python 3.5 - I specifically get a syntax error on 1_000_000.

Based on your knowledge, is this library's dependence on 3.6 based only on a couple syntax features? If so, would you be amenable to either changing these features, or accepting a pull request that uses 3.5 alternatives?

**Comment by bastibe** [comment]
Yes, it is only the syntax features. However, I would need all three implementations of SoundCard (Windows, macOS, Linux) to be compatible with 3.5 in order to change the requirement in setup.py.

**Comment by dkumor** [comment]
I have completed a PR with support for both linux and windows with Python 3.5 - mac files were not changed, sine they already used 3.5-compatible syntax. I'd appreciate it if you could take a quick look!
