### ISSUE TITLE
Record speaker output

### ISSUE THREAD

**Issue by sanderbrauwers** [bastibe/SoundCard#56]
Hi,

Is it possible to record my speaker output?

**Comment by slole** [comment]
Youp. When you list all your devices you should add this flag: `all_microphones(include_loopback=True)`. This works on Linux and Windows. The flag is there for macOS too, but it doesn't do anything.

**Comment by bastibe** [comment]
Exactly. Thank you, @slole!

**Comment by Raja18820** [comment]
Hi, I want to use this flag. Can you elaborate on how to use it?

**Comment by Raja18820** [comment]
I tried using this, but is not working for me. I tried playing some audio on my device and started recording using the mic by running the record() function in python. It just records some noise sounds instead of the speaker output.

**Comment by bastibe** [comment]
Please show us a complete code example of what you are trying to do, and a complete error message including a complete stack trace. Also, please tell us your Operating system, your Python version, and what version of SoundCard you are running.

**Comment by Raja18820** [comment]
import soundcard as sc
# get a list of all speakers:
speakers = sc.all_speakers() # i got list of speakers
# get the current default speaker on your system:
default_speaker = sc.default_speaker() #i made a deffault speaker
# get a list of all microphones:
mics = sc.all_microphones(include_loopback=True) #i got  a list of all microphone and made include_loopback enabled
# get the current default microphone on your system:
default_mic = sc.default_microphone() #i got  a default microphone 


one_speaker = sc.get_speaker('Realtek High Definition Audio')   # i got one speaker

one_mic = sc.get_microphone('Realtek High Definition Audio') #i got one mic with include_loopback enabled
#i started palying audio on my speaker and executed the below line
main_data = one_mic.record(samplerate=48000, numframes=480000)  
 
import numpy
import sounddevice as sd
sd.paly(main_data/numpy.max(main_data)) #this line is not giving me any output that I got at speaker
#instead plays some noise audio that is captured by mic

**Comment by bastibe** [comment]
I am getting tired of this exchange. This Github issue is not a place for general programming questions, nor is it a help desk for desperate students. It is for sorting out problems with SoundCard. Please respect that I am providing this help for you, for free, in my spare time.

So, if you want my help, please be as polite and helpful as you can, which includes formatting your responses in proper Markdown, and reading the documentation. 

Almost all of your ill-formatted code example is dead code. As an exercise, I would recommend trying to remove individual lines until only relevant code remains. Then please read through the documentation for the remaining lines. 

*Then*, and *only* then, please rephrase your question politely, with correct formatting, and including all necessary preconditions.

**Comment by Raja18820** [comment]
Sorry, @bastibe I am using GitHub newly. So, I actually commented on the code using a hashtag, it showed up a headline instead. Now I commented using ''' comment '''. This is just to know which flow I used. Can you please tell me how to utilize soundcard for grabbing the output of the speaker output and saving a numpy or a wav file.

**Comment by bastibe** [comment]
Github formats everything in Markdown: https://guides.github.com/features/mastering-markdown/  
Code examples should be wrapped in triple-backticks, or indented with four spaces.

Please complete the above exercise, then report back. Which lines in your code are actually necessary?

**Comment by Raja18820** [comment]
Yay! thanks, I was able to solve the issue for recording the speaker output. Can you help me without the usage of mic, how to get the numpy array of the speaker? Does this library work that way?

**Comment by bastibe** [comment]
You always record using a `microphone` and `recorder`. However, if you `all_microphones(include_loopback=True)` or `get_microphone(..., include_loopback=True)`, then you can get a `microphone` that records the output of a speaker (Windows and Linux only).

Does this answer your question?

**Comment by Raja18820** [comment]
Yes! I got it. Your information is helpful. Thanks! Is there any software that helps me grab the speaker signal as a numpy array without the help of mic?

**Comment by bastibe** [comment]
Why do you not want to use a `microphone`? If you want to record audio (even of a speaker), you need a `microphone`. You can't record audio without a `microphone`.

Am I misunderstanding you?

**Comment by Raja18820** [comment]
No no. You are not misunderstanding me. I was stuck in building a software which does the recording of a call and generates the two different wav files. One wav file consists of the mic inputs and one wav file consists of speaker outputs. So, I wanted to grab speaker output without mics help.

**Comment by bastibe** [comment]
So, if I understand you correctly, you have something like a Skype call, and you want to record the caller, without also recording the recipient, right?

This is a different problem, that SoundCard can not solve. *Skype* mixes the caller with the recipient, and plays them both on the speaker. There is nothing SoundCard can do to un-mix that signal.
