### ISSUE TITLE
I am having a run time error using play function

### ISSUE THREAD

**Issue by Raja18820** [bastibe/SoundCard#61]
Hello i am getting a run time error while using play() funciton

Here is the piece of code and error message
default_speaker.play(data/numpy.max(data), samplerate=48000)

--------------------------------------------------------------
    raise RuntimeError('Error {}'.format(hex(hresult+2**32)))

RuntimeError: Error 0x80070006

**Comment by bastibe** [comment]
What's your data, what's your operating system, what's your Python version?

**Comment by Raja18820** [comment]
I had used the same code that is shown in the tutorial of the code that you had mentioned. The data that is recorded is a numpy file. I am using 3.7 version of python. i am using 0.3.2 version sound card.

**Comment by bastibe** [comment]
What version of Windows, what is your data? I can't see your computer. Please help me help you.

**Comment by Raja18820** [comment]
I am using windows 10. My data is a numpy array the regular one that will be available after recording the audio. Its fine. I was able to play the audio with different library but it was showing up an error message instead of playing with soundcard.

**Comment by bastibe** [comment]
Like, how long is your data? How many channels? Does it contain NaNs? Is it bounded between [-1, 1]? What is your sound card?

"The regular one" is not descriptive. I need more information to reproduce your issue, or suggest fixes.

**Comment by Raja18820** [comment]
[1.xlsx](https://github.com/bastibe/SoundCard/files/3374369/1.xlsx)
I am attaching a excel file of a data that I am giving input to my play function. Data is (48000,2) long numpy array. It has 2 channels. No it doesn't have any nulls.No it is not bounded between -1 and 1. My sound card is "Realtek High Definition Audio".

**Comment by bastibe** [comment]
Thank you! Can you show me the entire stack trace of the error?

**Comment by Raja18820** [comment]
Traceback (most recent call last):

  File "<ipython-input-20-3d9cb17919c2>", line 1, in <module>
    default_speaker.play(main_data/numpy.max(main_data), samplerate = 48000)

  File "C:\Users\bhgajula\AppData\Local\Continuum\anaconda3\lib\site-packages\soundcard\mediafoundation.py", line 419, in play
    with self.player(samplerate, channels, blocksize) as p:

  File "C:\Users\bhgajula\AppData\Local\Continuum\anaconda3\lib\site-packages\soundcard\mediafoundation.py", line 416, in player
    return _Player(self._audio_client(), samplerate, channels, blocksize, False, exclusive_mode)

  File "C:\Users\bhgajula\AppData\Local\Continuum\anaconda3\lib\site-packages\soundcard\mediafoundation.py", line 523, in __init__
    _com.check_error(hr)

  File "C:\Users\bhgajula\AppData\Local\Continuum\anaconda3\lib\site-packages\soundcard\mediafoundation.py", line 88, in check_error
    raise RuntimeError('Error {}'.format(hex(hresult+2**32)))

RuntimeError: Error 0x80070006

**Comment by bastibe** [comment]
That's a weird spot for an error I have not seen before. Does it work with `exclusive_mode=True`?

I see you are using anaconda. How did you install SoundCard?

**Comment by Raja18820** [comment]
Upon checking with the documentation, the exclusive_mode parameter is for player function. Upon giving data in to the player() funciton it says invalid argument as I can't give data to the player() function.

**Comment by Raja18820** [comment]
I tried using the tag "exclusive_mode = True". It throws a run time error as invalid argument.

**Comment by bastibe** [comment]
> I tried using the tag "exclusive_mode = True". It throws a run time error as invalid argument.

Then you provided this *keyword argument* to the wrong function. But you didn't say or tell me which function you provided it to.

So show me complete code examples and complete stack traces, and format your questions correctly, or I will not be able to help you.

Information on formatting: https://guides.github.com/features/mastering-markdown/  
Information on SoundCard: https://soundcard.readthedocs.io/

**Comment by Raja18820** [comment]
Yay!! Thanks. It worked. I figured out where I was making an error. Thanks a lot.
