### ISSUE TITLE
first record results in float64, subsequent in float32

### ISSUE THREAD

**Issue by ipelupessy** [bastibe/SoundCard#62]
the following 
```
import soundcard

mics=soundcard.all_microphones()
mic=mics[1]
with mic.recorder(samplerate=48000, blocksize=4096, channels=1) as m:
  data=m.record(1024)
  print(data.dtype)
  data=m.record(1024)
  print(data.dtype)
  data=m.record(1024)
  print(data.dtype)
```
gives as output:
```
float64
float32
float32
```
while expected is:
```
float32
float32
float32
```

**Comment by ipelupessy** [comment]
I forgot to mention, this is on linux

**Comment by gonzalocasas** [comment]
I can confirm this behavior on Ubuntu 16.04

**Comment by bastibe** [comment]
Thank you for your bug report! That is some interesting behavior.

Would you like to investigate its cause? Any help would be greatly appreciated, as I don't have much time to work on this at the moment.

**Comment by gonzalocasas** [comment]
@bastibe I could perhaps help but I wouldn't know how to go about diagnosing this. If you give me some hints, I could test, since we have a fully reproducible setup.

**Comment by bastibe** [comment]
Never mind, it turns out the error was trivial. The latest commit should fix it.

**Comment by gonzalocasas** [comment]
I think this can be closed, right?

**Comment by ipelupessy** [comment]
think so too
