### ISSUE TITLE
output stream latency

### ISSUE THREAD

**Issue by gopalakr** [bastibe/SoundCard#68]
I am using the player context manager (loopback_player) with a _Blocksize_ _= None_ I am printing the latency of the player which shows it as 1.6 seconds.  When the same block of code is run with _Blocksize = 80_ latency is much lower (~2 ms)but the sound is chopped up and long.

I am running this in linux and I need minimal latency streaming of the audio output.

Any ideas whats happening here ?

**Comment by Chum4k3r** [comment]
You are sending stuff to hardware twice. Once by playing sound and a second by telling the machine to show in your screen the amount of time it takes to run. This is extremely expensive, there is a lot of syscalls in between, and these are even more expensive. 

[This article](http://www.rossbencina.com/code/real-time-audio-programming-101-time-waits-for-nothing) is very enlightening on this topic, it is a must-read

Hope it helps you
