### ISSUE TITLE
SoundCard fails to load mediafoundation.py.h when app built as a frozen/standalone exe

### ISSUE THREAD

**Issue by Dr3wBr3w** [bastibe/SoundCard#77]
When I attempt to run a compiled standalone "onefile" python exe created with PyInstaller + a python file that uses SoundCard, it crashes due to a file not found error. e.g.
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\YOUR-NAME\\YOUR-APP\\dist\\YOUR-APP-NAME\\soundcard\\mediafoundation.py.h'`

The error is caused by mediafoundation.py, specifically this part near the start where it loads mediafoundation.py.h:

```
_ffi = cffi.FFI()
_package_dir, _ = os.path.split(__file__)
with open(os.path.join(_package_dir, 'mediafoundation.py.h'), 'rt') as f:
    _ffi.cdef(f.read())
```

There needs to be a little bit more code added to check if it is running as a frozen exe (_MEIPASS) or via the normal/script way so the file can be located. Here's the documentation which explains it better and has a code example:
https://pyinstaller.readthedocs.io/en/stable/runtime-information.html

Another good explanation + code example: 
https://stackoverflow.com/a/13790741

**Comment by Dr3wBr3w** [comment]
I was able to build my app with PyInstaller onefile mode by inserting the following code at the start of mediafoundation.py (just before `with open` )

```
import sys

if getattr(sys, 'frozen', False):
    _package_dir = sys._MEIPASS
else:
    _package_dir, _ = os.path.split(__file__)
```

Then in the pyinstaller spec file for my app, edit the `a = Analysis `section `datas=[],` to be this (for Python 3.7):

`datas=[((os.environ['localappdata'] + '\\Programs\\Python\\Python37\\Lib\\site-packages\\soundcard\\mediafoundation.py.h'), '.'), ('chi.ico', '.')],`

**Comment by bastibe** [comment]
Is there a way to change SoundCard so it will work "out of the box" with pyinstaller?

If so, I'd be grateful for a pull request.

**Comment by Bob-Thomas** [comment]
@Dr3wBr3w you could also write a pyinstaller hook for this.
Currently, looking into it as well.

**Comment by Dr3wBr3w** [comment]
@bastibe @Bob-Thomas I'm just starting out and new to programming (I had to google what a "pull" request is! :) ), so I'm probably not the best person to do the request. I like the hook idea, if that can be done that will be easier than having to manually edit the spec file etc. Cheers!

**Comment by Bob-Thomas** [comment]
I can make a small pull request but instead of pull requesting soundcard which isn't really causing the issue I was thinking of making a pull request for pyinstaller with a simple hook-soundcard.py

```
from PyInstaller.utils.hooks import collect_data_files, collect_dynamic_libs

datas = collect_data_files('soundcard')
```

**Comment by bastibe** [comment]
Cool! That would be wonderful!

**Comment by Bob-Thomas** [comment]
https://github.com/pyinstaller/pyinstaller/pull/4834

**Comment by bastibe** [comment]
Beautiful! Thank you!
