### ISSUE TITLE
record speaker output without external noise 

### ISSUE THREAD

**Issue by charlamenan** [bastibe/SoundCard#78]
Is there a way to record speaker output without external noise getting captured .
And what is the difference between include_loopback=True and isloopback = True on microphone object 

for example :
import soundcard as sc
mic = sc.get_microphone("Stereo",include_loopback=True)
mic.isloopback = True #by default it is false even after the include_loopback=True

so i  think these two are with different purpose .
If i use the below code found from documentation,after adding one line (default_mic.isloopback = True) i am getting run time error .May i know how to use isloopback = True ?

import soundcard as sc
default_speaker = sc.default_speaker()
default_mic = sc.default_microphone()
default_mic.isloopback = True #new line i added 
with default_mic.recorder(samplerate=48000) as mic, \
  default_speaker.player(samplerate=48000) as sp:
  for _ in range(100):
    data = mic.record(numframes=1024)
    sp.play(data) 

Error message :
C:\Users\charlam\Documents\BIOS\Automation\Audiofile>python simul_play_record.py
Traceback (most recent call last):
  File "simul_play_record.py", line 5, in <module>
    with default_mic.recorder(samplerate=48000) as mic, \
  File "C:\Users\charlam\AppData\Local\Programs\Python\Python37\lib\site-packages\soundcard\mediafoundation.py", line 450, in recorder
    return _Recorder(self._audio_client(), samplerate, channels, blocksize, self.isloopback, exclusive_mode)
  File "C:\Users\charlam\AppData\Local\Programs\Python\Python37\lib\site-packages\soundcard\mediafoundation.py", line 523, in __init__
    _com.check_error(hr)
  File "C:\Users\charlam\AppData\Local\Programs\Python\Python37\lib\site-packages\soundcard\mediafoundation.py", line 88, in check_error
    raise RuntimeError('Error {}'.format(hex(hresult+2**32)))
RuntimeError: Error 0x88890003

my configuration :
Python 3.7.4

**Comment by slole** [comment]
The `include_loopback` flag is used to filter the devices, while `.isloopback` is simply used to check if the device that was returned is actually a loopback device and should not be modified/assigned.

Please check what devices you are actually receiving with:
`soundcard.all_microphones(include_loopback=True)`. 

The `get_microphone` function might be giving you an actual microphone instead of the speakers loopback device.

**Comment by charlamenan** [comment]
Thanks for the immediate reply ,yes you are right ,i get it now .thanks 

Another question ,not relented soundcard but if you know ?
I want to compare the recorded audio file of any audio format (.wav, .mp3 ,aac etc ) with the input file used for playback and say if both are same ,do not want byte wise comparison (bytes will not be same as a windows player is used for playback and there could be processed data )but to say recorded quality is good (noise and glitch free) ,How do i do that ,i see in internet saying fft can help ,but i do not see exact examples of code .can you help with python library or any input will unblock me .

**Comment by charlamenan** [comment]
May be sticking to single format for comparison also should be fine if there is a way to convert from(.mp3 and .aac) to .wav and stick with .wav format for comparison .

**Comment by slole** [comment]
For fft you might want to look into the rfft function of numpy (https://docs.scipy.org/doc/numpy/reference/generated/numpy.fft.rfft.html). You could then compare the fft results frame by frame, look for deviations... If you are not familiar with fft it is basically an algorithm that extracs the frequency information out of a signal (https://en.m.wikipedia.org/wiki/Fourier_transform).

I'm closing this issue since the original question has been answered.

**Comment by charlamenan** [comment]
Sure ,thank you so much .I did not expect that i will get response so quick .

**Comment by slole** [comment]
No problem, glad I could help.

**Comment by bastibe** [comment]
> I want to compare the recorded audio file of any audio format (.wav, .mp3 ,aac etc ) with the input file used for playback and say if both are same

If these files are digitally converted from the same source, you can simply subtract their waveforms and verify that the magnitude difference is smaller than some threshold.

But there are issues:

- compressed formats save inaudible parts at lesser resolution. Inaudible might mean a silent low-frequency noise during a loud crescendo at a different frequency. Humans can't hear quiet nuances while a nearby frequency is loud. But computers and waveforms sure can. So a simple difference might not work well for some signals.
- if the signals don't start at the same time, you'll need to lag-correct them before subtraction. You might find the correct lag using an autocorrelation. This can happen during format conversions as well.
- if the signals were resampled, you'll need to resample them back to a common time base, and correct for the high-frequency loss to get a comparable difference.
- if there was a microphone involved somewhere, the sampling rate will be subtly different. Every sound card has its own time base, even when the pre-set sampling rate is identical, and they drift quite quickly. So you'll need to stretch signals to match. This is a thoroughly non-trivial problem.

**Comment by charlamenan** [comment]
Hi Bastibe,

could you please explain with some example code .

I do not understand ,files digitally converted from same sources ?

**Comment by bastibe** [comment]
I mean if your files are simply converted files. I.e. if you converted an mp3 to a wav using some kind of audio editor. In that case, it should be relatively easy to compare them.

Any other case, it's a hard problem.

**Comment by charlamenan** [comment]
I am looking for a solution for wav file only for now .May i know the example code in python to subtract their waveforms and verify that the magnitude difference is smaller than some threshold.Sorry that i am asking direct solution, i have been on this problem for a long time .

**Comment by bastibe** [comment]
```python
numpy.mean(numpy.abs(waveform1 - waveform2)) < threshold
```

But as I said, this will ONLY work if there is no difference in sampling, and no lag between them.

**Comment by charlamenan** [comment]
Hi bastibe ,

Here waveform1 and waveform2 ,i understand it as fft of samples (i am calculating fft at every 1s samples )from both files and then subtract .I see the subtraction values changes drastically at every 1 sec , i think that should not be the case .The threshold value should be same across every 1sec .am i right ?May i contact you by other means so that i can explain my problem well ?

As a experiment the above fft and subtraction i have done it on the same file (just renaming same file as file1 and file2) then i see the subtraction value as zero (numpy.mean(numpy.abs(waveform1 - waveform2)))

[AudioFiles.zip](https://github.com/bastibe/SoundCard/files/4386470/AudioFiles.zip)
![audacity](https://user-images.githubusercontent.com/62550871/77635573-cc25a800-6f78-11ea-9993-75ea58270a23.JPG)

Attached the input file used for playback and the recorded (loopback speaker )file.

code used :
`import soundcard as sc
import numpy as np
import subprocess
import soundfile as sf

#Groove music command line 
GROOVE_PLAYER_CMD = \
    'cmd /c start "explorer.exe shell:C:\Program Files\WindowsApps\Microsoft.' \
    'ZuneMusic_3.6.25021.0_x64__8wekyb3d8bbwe!Microsoft.ZuneMusic" '

#Get llopback speaker 
mics = sc.all_microphones(include_loopback=True)
loopback_speaker = mics[1]
print("loopback_speaker:",loopback_speaker)

if loopback_speaker.isloopback == True:
	print("loopback is supported")
else:
	print("loopback is not supported")

file_path = "input.wav"
fs_rate, signal = sf.read(file_path)
f = sf.SoundFile(file_path)

total_frames = len(f)
fs_rate = f.samplerate

with loopback_speaker.recorder(samplerate=fs_rate) as mic:

  groove_play = GROOVE_PLAYER_CMD+file_path
  cmd_exe = subprocess.Popen(groove_play, shell=True, stdout=subprocess.PIPE,
                               stderr=subprocess.STDOUT, stdin=subprocess.PIPE)
  print("Playback started in groove music player")
  print("Recording started")
  data = mic.record(numframes=(total_frames)) #recoding more than the playback file totalframes
  print("Recording ended")
  
  
  exec_out = cmd_exe.communicate()[0]
  print("Playback ended")

  sf.write('recorded.wav', data, fs_rate)`

**Comment by bastibe** [comment]
You can see in your screenshot that the waveforms do not look all that similar. You can subtract them and save the difference as a new file. Check out the differences and figure out their cause.

But really... it's just a hard problem. I have given you a number of suggestions. But that's all I can do here. This Github issue is a place for discussing problems with SoundCard, not general DSP questions. Perhaps someone else wants to jump in and help you further, but I don't have the time to do that right now. Sorry.

Perhaps the folks at https://dsp.stackexchange.com/ can help you with your problem.

**Comment by charlamenan** [comment]
Thanks Bastibe for the info :)
