### ISSUE TITLE
Is Soundcard specific to Python 3 ? 

### ISSUE THREAD

**Issue by mpariente** [bastibe/SoundCard#8]
I installed soundcard in Python 2.7. 

If I run `import soundcard`, it raises : 
`NotImplementedError: SoundCard does not support linux2 yet`
which comes from `__init__.py`. 

In Python 3, sys.platform return `'linux'` for every version of it but in Python 2.7 sys.platform will return `'linux2'` or `'linux3'`. 
If this is the only part of the code which is not compatible with Python 2.7, we can replace the line by 
`if sys.platform.startswith('linux'): `

**Comment by bastibe** [comment]
I haven't tried it in Python 2.7.
