### ISSUE TITLE
Add git tags for patch releases

### ISSUE THREAD

**Issue by flying-sheep** [bastibe/SoundCard#84]
The latest tag is still 0.2.0 while 0.3.3 has already been released:

```console
$  git describe --long --tags
0.2.0-44-gc03a9f9
```

**Comment by bastibe** [comment]
I tagged 0.3.3, thank you for reminding me.

**Comment by flying-sheep** [comment]
Great, thank you!

**Comment by flying-sheep** [comment]
Oh, you accidentally tagged the 0.2.0 commit as 0.3.3 too!

**Comment by bastibe** [comment]
Silly me. Apparently my checked out version was very old on this particular computer, and the commit message of 0.2.0 was deceptively similar to 0.3.3, so I mistook them. Sorry about that.
