### ISSUE TITLE
How to record from speaker?

### ISSUE THREAD

**Issue by PasaOpasen** [bastibe/SoundCard#91]
Can I record sounds from speakers?

Used code like this

# record some music from speaker
data = default_speaker.record(samplerate=48000, numframes=48000)
# repeat it
default_speaker.play(data/numpy.max(data), samplerate=48000)

**Comment by slole** [comment]
When getting the recording devices with `sc.all_microphones()`, you can set the flag `include_loopback` like so: `sc.all_microphones(include_loopback=true)`. This will include monitor devices on linux and loopback devices on windows. This is not supported on macOS.

**Comment by PasaOpasen** [comment]
thank u, I will try!
