### ISSUE TITLE
using SoundCard from program with callbacks?

### ISSUE THREAD

**Issue by rikvanriel** [bastibe/SoundCard#97]
Hello,

I am trying to use the SoundCard library from a program that is structured roughly like this:

main loop, in a websocket handling class:
   - get control data from network server (a kiwisdr)
     - callback into class that processes audio
     - get sample rate from the received control data
        -> would like to set up speaker.player here
   - get audio samples from network server
      - callback into class that processes audio
      - audio processing function
          -> would like to use speaker.player here

Unfortunately it looks like the _Player and _Stream classes, returned by speaker.player can only be used in a with .... as ... construction, which would require that I set the sample rate before I have discovered the sample rate from the network.

Is there any way to use the SoundCard library in such a program, or is it not suitable for use from programs where sound playback is something called from the main loop, but not the main loop itself?

**Comment by bastibe** [comment]
Instead of using the `with` context manager, you can call `__enter__` and `__exit__` yourself.

That said, it might make more sense to store off the sample rate when you receive it, and only instantiate the player once you actually receive audio data.

**Comment by rikvanriel** [comment]
I cannot instantiate the player from inside the audio processing function, because that function gets invoked every time another packet of audio is received off the network, and all those samples belong to the same audio stream.

I tried calling __enter__ directly, but that seems to result in _Player.stream not being set up:

`            self._output_sample_rate = int(self._sample_rate)
             self.player = self.speaker.player(samplerate=self._output_sample_r  ate, blocksize=4096)
             self.player.__enter__
              print("self.player.stream = ", self.player.stream)
`
The above results in this error:

`
    print("self.player.stream = ", self.player.stream)
AttributeError: '_Player' object has no attribute 'stream'
`

I also inserted a print in the _Stream __enter__ function right at the start, and it never prints anything. Should calling __enter__ on the _Player object automatically invoke __enter__ on the _Stream object, or do I need to do something special to make that happen?

**Comment by rikvanriel** [comment]
BTW, if you are curious, I am working on the kiwiclientd.py file in this repo/branch, based off of the kiwirecorder.py program in the same repository. The interesting code is in the KiwiSoundRecorder class, where I instantiate the speaker and player objects, and attempt to use them.

https://github.com/rikvanriel/kiwiclient/tree/riel/kiwiclientd

**Comment by rikvanriel** [comment]
Looks like adding () to the end of the line worked. Calling self.player.__enter__() did the trick.

Now the audio is streaming, and I can go hunt for over/underflow and other issues :)
